# Copyright IBM Corp. All Rights Reserved.
#
# SPDX-License-Identifier: Apache-2.0
#

version: '2'

networks:
  chainedbids:

services:

  orderer.chainedbids.uva.es:
    extends:
      file:   base/docker-compose-base.yaml
      service: orderer.chainedbids.uva.es
    container_name: orderer.chainedbids.uva.es
    networks:
      - chainedbids

  peer0.people.chainedbids.uva.es:
    container_name: peer0.people.chainedbids.uva.es
    extends:
      file:  base/docker-compose-base.yaml
      service: peer0.people.chainedbids.uva.es
    networks:
      - chainedbids

  peer1.people.chainedbids.uva.es:
    container_name: peer1.people.chainedbids.uva.es
    extends:
      file:  base/docker-compose-base.yaml
      service: peer1.people.chainedbids.uva.es
    networks:
      - chainedbids

  peer2.people.chainedbids.uva.es:
    container_name: peer2.people.chainedbids.uva.es
    extends:
      file:  base/docker-compose-base.yaml
      service: peer2.people.chainedbids.uva.es
    networks:
      - chainedbids

  peer0.firms.chainedbids.uva.es:
    container_name: peer0.firms.chainedbids.uva.es
    extends:
      file:  base/docker-compose-base.yaml
      service: peer0.firms.chainedbids.uva.es
    networks:
      - chainedbids

  peer1.firms.chainedbids.uva.es:
    container_name: peer1.firms.chainedbids.uva.es
    extends:
      file:  base/docker-compose-base.yaml
      service: peer1.firms.chainedbids.uva.es
    networks:
      - chainedbids

  cli:
    container_name: cli
    image: hyperledger/fabric-tools
    tty: true
    environment:
      - GOPATH=/opt/gopath
      - CORE_VM_ENDPOINT=unix:///host/var/run/docker.sock
      - CORE_LOGGING_LEVEL=DEBUG
      - CORE_PEER_ID=cli
      - CORE_PEER_ADDRESS=peer0.people.chainedbids.uva.es:7051
      - CORE_PEER_LOCALMSPID=peopleMSP
      - CORE_PEER_TLS_ENABLED=true
      - CORE_PEER_TLS_CERT_FILE=/opt/gopath/src/github.com/hyperledger/fabric/peer/crypto/peerOrganizations/people.chainedbids.uva.es/peers/peer0.people.chainedbids.uva.es/tls/server.crt
      - CORE_PEER_TLS_KEY_FILE=/opt/gopath/src/github.com/hyperledger/fabric/peer/crypto/peerOrganizations/people.chainedbids.uva.es/peers/peer0.people.chainedbids.uva.es/tls/server.key
      - CORE_PEER_TLS_ROOTCERT_FILE=/opt/gopath/src/github.com/hyperledger/fabric/peer/crypto/peerOrganizations/people.chainedbids.uva.es/peers/peer0.people.chainedbids.uva.es/tls/ca.crt
      - CORE_PEER_MSPCONFIGPATH=/opt/gopath/src/github.com/hyperledger/fabric/peer/crypto/peerOrganizations/people.chainedbids.uva.es/users/Admin@people.chainedbids.uva.es/msp
    working_dir: /opt/gopath/src/github.com/hyperledger/fabric/peer
    command: /bin/bash -c './scripts/script.sh ${CHANNEL_NAME} ${DELAY}; sleep $TIMEOUT'
    volumes:
        - /var/run/:/host/var/run/
        - ./chaincode/:/opt/gopath/src/github.com/hyperledger/fabric/examples/chaincode/go
        - ./crypto-config:/opt/gopath/src/github.com/hyperledger/fabric/peer/crypto/
        - ./scripts:/opt/gopath/src/github.com/hyperledger/fabric/peer/scripts/
        - ./channel-artifacts:/opt/gopath/src/github.com/hyperledger/fabric/peer/channel-artifacts
    depends_on:
      - orderer.chainedbids.uva.es
      - peer0.people.chainedbids.uva.es
      - peer1.people.chainedbids.uva.es
      - peer2.people.chainedbids.uva.es
      - peer0.firms.chainedbids.uva.es
      - peer1.firms.chainedbids.uva.es
    networks:
      - chainedbids

